Repository 0mad/yolobook, pull requests merged in 2019-06, with the labels that each got.

#37 #29 컴포넌트 - 뷰어
  frontend/components/Viewer/Viewer.scss
  frontend/components/Viewer/Viewer.stories.tsx
  frontend/components/Viewer/Viewer.tsx
  frontend/components/Viewer/index.tsx
Labels: develop

#34 #7 컴포넌트 - 로그인
  frontend/components/Login/Login.scss
  frontend/components/Login/Login.stories.tsx
  frontend/components/Login/Login.tsx
  frontend/components/Login/LoginButton.scss
  frontend/components/Login/LoginButton.tsx
  frontend/components/Login/index.ts
  frontend/containers/LoginContainer.tsx
  frontend/package-lock.json
  frontend/static/images/naver-logo.png
Labels: develop

#39 #31 컴포넌트 - 배너
  frontend/components/Banner/Banner.scss
  frontend/components/Banner/Banner.stories.tsx
  frontend/components/Banner/Banner.tsx
  frontend/components/Banner/index.ts
Labels: develop

#40 #32 next-routes 적용 및 mobx 구조 잡기
  frontend/package.json
  frontend/pages/_app.tsx
  frontend/pages/anatomy.tsx
  frontend/pages/login.tsx
  frontend/routes.js
  frontend/server.js
  frontend/stores/index.ts
  frontend/stores/modules/common.ts
  frontend/stores/modules/index.ts
Labels: develop

#43 #42 frontend proxy 설정
  frontend/package.json
  frontend/server.js
Labels: develop

#38 #30 컴포넌트 - 사용자 정보
  frontend/components/UserInfo/UserInfo.scss
  frontend/components/UserInfo/UserInfo.stories.tsx
  frontend/components/UserInfo/UserInfo.tsx
  frontend/components/UserInfo/index.ts
Labels: develop

#44 #41 컴포넌트 - 둘러보기 헤더
  frontend/.storybook/webpack.config.js
  frontend/components/Login/Login.scss
  frontend/components/Login/Login.stories.tsx
  frontend/components/Login/Login.tsx
  frontend/components/Login/LoginButton.scss
  frontend/components/Login/LoginFooter.scss
  frontend/components/Login/LoginFooter.tsx
  frontend/components/Login/LoginHeader.scss
  frontend/components/Login/LoginHeader.tsx
  frontend/components/Login/LoginTemplate.scss
  frontend/components/common/Header/Header.scss
  frontend/components/common/Header/Header.stories.tsx
  frontend/components/common/Header/Header.tsx
  frontend/components/common/PageTemplate/PageTemplate.scss
Labels: develop

#35 #26 컴포넌트 - 포스트
  frontend/components/Post/Post.scss
  frontend/components/Post/Post.stories.tsx
  frontend/components/Post/Post.tsx
  frontend/components/Post/PostGallery.scss
  frontend/components/Post/PostGallery.tsx
  frontend/components/Post/index.ts
Labels: develop

#36 #25 컴포넌트 - 갤러리
  frontend/.storybook/config.js
  frontend/components/Gallery/Gallery.scss
  frontend/components/Gallery/Gallery.stories.tsx
  frontend/components/Gallery/Gallery.tsx
  frontend/components/Gallery/GalleryPhoto.scss
  frontend/components/Gallery/GalleryPhoto.tsx
  frontend/components/Gallery/index.ts
Labels: develop

#46 #45 컴포넌트 - 댓글
  frontend/.storybook/addons.js
  frontend/.storybook/config.js
  frontend/components/Comment/Comment.scss
  frontend/components/Comment/Comment.stories.tsx
  frontend/components/Comment/Comment.tsx
  frontend/components/Comment/CommentEditor.scss
  frontend/components/Comment/CommentEditor.tsx
  frontend/components/Comment/CommentItem.scss
  frontend/components/Comment/CommentItem.tsx
  frontend/components/Comment/index.ts
  frontend/components/Login/LoginFooter.scss
  frontend/components/common/Header/Header.scss
  frontend/package.json
  frontend/tslint.json
Labels: develop

#50 #49 페이지 템플릿 - 너비 래핑하기
  frontend/components/common/PageTemplate/PageTemplate.scss
  frontend/components/common/PageTemplate/PageTemplate.tsx
Labels: develop

#51 #12 사용자 정보 페이지 - 소개
  frontend/components/Banner/Banner.tsx
  frontend/components/common/ContentLayout/ContentLayout.scss
  frontend/components/common/ContentLayout/ContentLayout.tsx
  frontend/components/common/ContentLayout/index.ts
  frontend/containers/BannerContainer.tsx
  frontend/containers/UserInfoContainer.tsx
  frontend/pages/profile/info.tsx
  frontend/routes.js
Labels: develop

#52 #48 컴포넌트 - 포스트 래퍼
  frontend/components/Comment/Comment.scss
  frontend/components/Comment/Comment.tsx
  frontend/components/Comment/CommentEditor.scss
  frontend/components/Comment/index.ts
  frontend/components/Post/Post.scss
  frontend/components/Post/Post.stories.tsx
  frontend/components/Post/Post.tsx
  frontend/components/Post/PostGallery.scss
  frontend/components/Post/PostGallery.tsx
  frontend/components/PostWrapper/PostWrapper.scss
  frontend/components/PostWrapper/PostWrapper.stories.tsx
  frontend/components/PostWrapper/PostWrapper.tsx
Labels: develop

#54 #28 컴포넌트 - 친구
  frontend/components/Friend/Friend.scss
  frontend/components/Friend/Friend.stories.tsx
  frontend/components/Friend/Friend.tsx
  frontend/components/Friend/FriendItem.scss
  frontend/components/Friend/FriendItem.tsx
  frontend/components/Friend/index.ts
  frontend/components/common/Button/Button.scss
Labels: develop

#53 #9 타임라인 페이지
  frontend/components/PostWrapper/PostWrapper.tsx
  frontend/components/PostWrapper/index.ts
  frontend/components/common/Header/Header.scss
  frontend/components/common/PageTemplate/PageTemplate.scss
  frontend/containers/EditorContainer.tsx
  frontend/containers/PostContainer.tsx
  frontend/pages/_app.tsx
  frontend/pages/timeline.tsx
  frontend/routes.js
Labels: develop

#56 #14 사용자 정보 페이지 - 사진
  frontend/components/Banner/Banner.tsx
  frontend/components/Friend/Friend.scss
  frontend/components/Friend/Friend.stories.tsx
  frontend/components/Friend/Friend.tsx
  frontend/components/Friend/FriendItem.scss
  frontend/components/Friend/FriendItem.tsx
  frontend/components/Friend/index.ts
  frontend/components/Gallery/Gallery.tsx
  frontend/components/Gallery/GalleryPhoto.tsx
  frontend/components/Gallery/index.ts
  frontend/components/PostWrapper/PostWrapper.tsx
  frontend/components/PostWrapper/index.ts
  frontend/components/common/Button/Button.scss
  frontend/components/common/Header/Header.scss
  frontend/components/common/PageTemplate/PageTemplate.scss
  frontend/containers/EditorContainer.tsx
  frontend/containers/PictureContainer.tsx
  frontend/containers/PostContainer.tsx
  frontend/pages/_app.tsx
  frontend/pages/profile/picture.tsx
  frontend/pages/timeline.tsx
  frontend/routes.js
Labels: develop

#58 #57 컴포넌트 - 친구 목록
  frontend/components/Friend/Friend.scss
  frontend/components/Friend/Friend.stories.tsx
  frontend/components/Friend/Friend.tsx
  frontend/components/Friend/FriendItem.scss
  frontend/components/Friend/FriendList.scss
  frontend/components/Friend/FriendList.tsx
Labels: develop

#59 #13 사용자 정보 페이지 - 친구
  frontend/components/Banner/Banner.tsx
  frontend/components/Friend/index.ts
  frontend/containers/FriendContainer.tsx
  frontend/pages/profile/friend.tsx
  frontend/routes.js
  frontend/styles/base.scss
Labels: develop

#60 #55 컴포넌트 친구 요청
  frontend/components/Friend/Friend.stories.tsx
  frontend/components/Friend/FriendRequest.scss
  frontend/components/Friend/FriendRequest.tsx
Labels: develop

#62 #61 인덱스 페이지
  frontend/components/Banner/Banner.tsx
  frontend/components/common/ContentLayout/ContentLayout.scss
  frontend/components/common/ContentLayout/ContentLayout.tsx
  frontend/pages/index.tsx
  frontend/pages/profile/friend.tsx
  frontend/pages/profile/info.tsx
  frontend/pages/profile/picture.tsx
  frontend/pages/profile/timeline.tsx
  frontend/pages/timeline.tsx
  frontend/routes.js
Labels: develop

#65 #22 백엔드 개발환경 구축
  backend/.env
  backend/.gitignore
  backend/.prettierrc.js
  backend/package-lock.json
  backend/package.json
  backend/src/app.ts
  backend/src/config/index.js
  backend/src/lib/crypto.ts
  backend/src/lib/token.ts
  backend/src/logger.ts
  backend/src/models/Account.ts
  backend/src/routes/auth/auth.controller.ts
  backend/src/routes/auth/index.ts
  backend/src/routes/auth/ref.auth.controller.ts
  backend/src/routes/index.ts
  backend/src/routes/post/index.ts
  backend/src/routes/post/post.controller.ts
  backend/src/routes/user/index.ts
  backend/src/routes/user/user.controller.ts
  backend/src/sequelize.ts
  backend/tsconfig.json
  backend/tslint.json
  frontend/package.json
Labels: develop

#66 #64 친구 요청 페이지
  frontend/components/Follow/Follow.scss
  frontend/components/Follow/Follow.stories.tsx
  frontend/components/Follow/Follow.tsx
  frontend/components/Follow/index.ts
  frontend/components/Friend/Friend.stories.tsx
  frontend/components/common/Header/Header.scss
  frontend/components/common/Header/Header.tsx
  frontend/containers/FollowContainer.tsx
  frontend/pages/follow.tsx
  frontend/routes.js
Labels: develop

#68 #67 구글 로그인
  .vscode/launch.json
  backend/package.json
  backend/src/models/Account.ts
  backend/src/routes/auth/auth.controller.ts
  backend/tslint.json
  frontend/.env
  frontend/api/auth.ts
  frontend/components/Login/Login.tsx
  frontend/components/Login/LoginButton.tsx
  frontend/containers/CommonContainer.tsx
  frontend/containers/LoginContainer.tsx
  frontend/lib/storage.ts
  frontend/package.json
  frontend/pages/_app.tsx
  frontend/stores/modules/AuthStore.ts
  frontend/stores/modules/CommonStore.ts
  frontend/stores/modules/UserStore.ts
  frontend/stores/modules/index.ts
Labels: develop

#71 #63 태그로 다른 페이지 이동시 페이지 렌더링이 재대로 안되는 문제 해결
  frontend/pages/_app.tsx
Labels: bug

#73 #72 dotenv 셋팅
  frontend/.env.sample
  frontend/components/Login/Login.tsx
  frontend/next.config.js
  frontend/package.json
Labels: develop

#77 #70 카카오 로그인
  frontend/.env.sample
  frontend/components/Login/Login.tsx
  frontend/containers/LoginContainer.tsx
  frontend/package.json
Labels: develop

#83 #78 게시물 작성 및 뷰잉 - 서버 연동
  backend/.gitignore
  backend/package.json
  backend/src/app.ts
  backend/src/models/Account.ts
  backend/src/models/Post.ts
  backend/src/models/PostImage.ts
  backend/src/routes/auth/auth.controller.ts
  backend/src/routes/auth/ref.auth.controller.ts
  backend/src/routes/middlewares.ts
  backend/src/routes/post/index.ts
  backend/src/routes/post/post.controller.ts
  frontend/.env.sample
  frontend/api/auth.ts
  frontend/api/post.ts
  frontend/components/Comment/Comment.tsx
  frontend/components/Editor/Editor.scss
  frontend/components/Editor/Editor.tsx
  frontend/components/Login/Login.tsx
  frontend/components/Login/LoginNaver.scss
  frontend/components/Login/LoginNaver.tsx
  frontend/components/Post/Post.tsx
  frontend/components/Post/PostGallery.tsx
  frontend/components/PostWrapper/PostWrapper.tsx
  frontend/containers/EditorContainer.tsx
  frontend/containers/LoginContainer.tsx
  frontend/containers/PostContainer.tsx
  frontend/next.config.js
  frontend/package.json
  frontend/pages/_app.tsx
  frontend/server.js
  frontend/stores/modules/AuthStore.ts
  frontend/stores/modules/PostStore.ts
  frontend/stores/modules/index.ts
  frontend/styles/base.scss
Labels: develop

#88 #76 로그인, 로그아웃 마무리
  backend/src/routes/auth/auth.controller.ts
  frontend/components/Editor/Editor.stories.tsx
  frontend/components/Editor/Editor.tsx
  frontend/components/Login/LoginNaver.scss
  frontend/components/Login/LoginNaver.tsx
  frontend/components/common/Header/Header.stories.tsx
  frontend/components/common/Header/Header.tsx
  frontend/components/common/PageTemplate/PageTemplate.tsx
  frontend/containers/CommonContainer.tsx
  frontend/containers/EditorContainer.tsx
  frontend/containers/HeaderContainer.tsx
  frontend/containers/LoginContainer.tsx
  frontend/lib/storage.ts
  frontend/next.config.js
  frontend/stores/modules/AuthStore.ts
  frontend/stores/modules/UserStore.ts
  frontend/stores/modules/index.ts
Labels: develop

#92 #84 포스트 작성하면 성공/실패 알림 다이얼로그와 포스트 작성 컴포넌트 상태 초기화
  backend/public/images/default_thumbnail.png
  backend/src/app.ts
  backend/src/routes/post/post.controller.ts
  frontend/components/Editor/Editor.tsx
  frontend/containers/EditorContainer.tsx
  frontend/containers/PostContainer.tsx
  frontend/server.js
  frontend/stores/modules/PostStore.ts
Labels: develop

#91 #80 검색 기능 구현
  backend/src/routes/user/index.ts
  backend/src/routes/user/user.controller.ts
  frontend/api/follow.ts
  frontend/api/user.ts
  frontend/components/Follow/Follow.stories.tsx
  frontend/components/common/Header/Header.scss
  frontend/components/common/Header/Header.stories.tsx
  frontend/components/common/Header/Header.tsx
  frontend/components/common/Header/HeaderSearchBar.scss
  frontend/components/common/Header/HeaderSearchBar.tsx
  frontend/components/common/Header/index.ts
  frontend/components/common/PageTemplate/PageTemplate.tsx
  frontend/containers/HeaderContainer.tsx
  frontend/stores/modules/CommonStore.ts
Labels: develop

#100 #99 코드 개선 및 정리
  backend/src/routes/user/index.ts
  backend/src/routes/user/user.controller.ts
  frontend/api/follow.ts
  frontend/api/user.ts
  frontend/components/Comment/Comment.tsx
  frontend/components/Editor/Editor.tsx
  frontend/components/Follow/Follow.stories.tsx
  frontend/components/Follow/Follow.tsx
  frontend/components/Login/Login.tsx
  frontend/components/Login/LoginHeader.tsx
  frontend/components/Login/LoginNaver.tsx
  frontend/components/common/Header/Header.scss
  frontend/components/common/Header/Header.stories.tsx
  frontend/components/common/Header/Header.tsx
  frontend/components/common/Header/HeaderSearchBar.scss
  frontend/components/common/Header/HeaderSearchBar.tsx
  frontend/components/common/Header/index.ts
  frontend/components/common/PageTemplate/PageTemplate.tsx
  frontend/containers/BannerContainer.tsx
  frontend/containers/CommonContainer.tsx
  frontend/containers/EditorContainer.tsx
  frontend/containers/FollowContainer.tsx
  frontend/containers/FriendContainer.tsx
  frontend/containers/HeaderContainer.tsx
  frontend/containers/LoginContainer.tsx
  frontend/containers/PictureContainer.tsx
  frontend/containers/PostContainer.tsx
  frontend/containers/UserInfoContainer.tsx
  frontend/stores/modules/CommonStore.ts
  frontend/stores/modules/FollowStore.ts
  frontend/stores/modules/UserStore.ts
Labels: enhance

#107 #102 프로필 썸네일과 커버 사진 업데이트
  backend/src/lib/multer.ts
  backend/src/lib/token.ts
  backend/src/models/Account.ts
  backend/src/routes/auth/auth.controller.ts
  backend/src/routes/auth/index.ts
  backend/src/routes/post/index.ts
  backend/src/routes/post/post.controller.ts
  backend/src/routes/user/index.ts
  backend/src/routes/user/user.controller.ts
  frontend/api/user.ts
  frontend/components/Banner/Banner.scss
  frontend/components/Banner/Banner.tsx
  frontend/components/Post/Post.tsx
  frontend/components/PostWrapper/PostWrapper.tsx
  frontend/components/common/Header/Header.tsx
  frontend/containers/BannerContainer.tsx
  frontend/containers/BeforeMountComponent.tsx
  frontend/containers/CommonContainer.tsx
  frontend/containers/EditorContainer.tsx
  frontend/containers/HeaderContainer.tsx
  frontend/containers/LoginContainer.tsx
  frontend/pages/_app.tsx
  frontend/stores/modules/ProfileStore.ts
  frontend/stores/modules/UserStore.ts
  frontend/stores/modules/index.ts
Labels: develop

#104 #101 FollowStore 개선
  backend/src/routes/follow/follow.controller.ts
  frontend/containers/FollowContainer.tsx
  frontend/stores/modules/FollowStore.ts
Labels: enhance

#111 #82 폰트 사이즈 조정
  frontend/components/Banner/Banner.scss
  frontend/components/Comment/CommentEditor.scss
  frontend/components/Comment/CommentItem.scss
  frontend/components/Follow/Follow.scss
  frontend/components/Friend/FriendList.scss
  frontend/components/Gallery/Gallery.scss
  frontend/components/Login/Login.scss
  frontend/components/Login/Login.tsx
  frontend/components/Login/LoginButton.scss
  frontend/components/Login/LoginFooter.scss
  frontend/components/Login/LoginFooter.tsx
  frontend/components/Login/LoginHeader.scss
  frontend/components/Login/LoginTemplate.scss
  frontend/components/Post/Post.scss
  frontend/components/PostWrapper/PostWrapper.scss
  frontend/components/UserInfo/UserInfo.scss
  frontend/components/common/Button/Button.scss
  frontend/components/common/Header/Header.scss
  frontend/components/common/Header/Header.tsx
  frontend/static/.DS_Store
  frontend/static/images/logo.png
  frontend/static/images/naver-logo.png
Labels: enhance

#123 #119 배포 환경에서 네이버 로그인 버그
  frontend/components/Login/LoginNaver.tsx
  frontend/containers/BeforeMountComponent.tsx
  frontend/server.js
Labels: bug

#125 #110 커버 사진 없을 때 빈 배경색이 나오도록 처리
  frontend/components/Banner/Banner.tsx
Labels: bug

#124 #120 포스트 작성 버그 및 타임라인 스타일 개선
  frontend/components/Banner/Banner.scss
  frontend/components/Comment/CommentEditor.scss
  frontend/components/Friend/FriendList.scss
  frontend/components/Login/LoginFooter.scss
  frontend/components/Login/LoginHeader.scss
  frontend/components/Post/Post.scss
  frontend/components/PostWrapper/PostWrapper.scss
  frontend/components/Timeline/Timeline.scss
  frontend/components/Timeline/Timeline.tsx
  frontend/components/Timeline/index.tsx
  frontend/components/common/ContentLayout/ContentLayout.scss
  frontend/components/common/ContentLayout/ContentLayout.tsx
  frontend/components/common/ContentLayout/index.ts
  frontend/components/common/Header/Header.scss
  frontend/components/common/Header/HeaderSearchBar.scss
  frontend/components/common/PageTemplate/PageTemplate.scss
  frontend/containers/EditorContainer.tsx
  frontend/containers/TimelineContainer.tsx
  frontend/pages/follow.tsx
  frontend/pages/index.tsx
  frontend/pages/profile/friend.tsx
  frontend/pages/profile/info.tsx
  frontend/pages/profile/picture.tsx
  frontend/pages/profile/timeline.tsx
  frontend/stores/modules/PostStore.ts
Labels: enhance

#126 #121 포스트 에디터 및 뷰잉 개선
  backend/src/models/Post.ts
  frontend/components/Post/Post.scss
  frontend/components/Post/Post.stories.tsx
  frontend/components/Post/Post.tsx
  frontend/components/Post/PostGallery.scss
  frontend/components/Post/PostGallery.tsx
  frontend/components/PostWrapper/PostWrapper.tsx
  frontend/components/Viewer/Viewer.scss
  frontend/components/Viewer/Viewer.tsx
  frontend/containers/PostContainer.tsx
  frontend/containers/TimelineContainer.tsx
  frontend/containers/ViewerContainer.tsx
  frontend/stores/modules/ViewerStore.ts
  frontend/stores/modules/index.ts
  frontend/styles/utils/_variables.scss
  frontend/utils/getCoolDate.ts
Labels: develop, enhance
