Repository 0mad/yolobook, pull requests merged in 2019-07, with the labels that each got.

#130 #122 사용자 정보 - 친구, 사진 보이기
  backend/src/routes/follow/follow.controller.ts
  backend/src/routes/follow/index.ts
  backend/src/routes/post/index.ts
  backend/src/routes/post/post.controller.ts
  frontend/api/follow.ts
  frontend/api/post.ts
  frontend/api/user.ts
  frontend/components/Banner/Banner.tsx
  frontend/components/Friend/Friend.stories.tsx
  frontend/components/Friend/FriendItem.scss
  frontend/components/Friend/FriendItem.tsx
  frontend/components/Friend/FriendList.scss
  frontend/components/Friend/FriendList.tsx
  frontend/components/Gallery/Gallery.scss
  frontend/components/Gallery/Gallery.stories.tsx
  frontend/components/Gallery/Gallery.tsx
  frontend/components/Gallery/GalleryPhoto.tsx
  frontend/components/Viewer/Viewer.stories.tsx
  frontend/components/Viewer/Viewer.tsx
  frontend/components/common/Header/Header.tsx
  frontend/containers/BannerContainer.tsx
  frontend/containers/FriendContainer.tsx
  frontend/containers/PictureContainer.tsx
  frontend/containers/TimelineContainer.tsx
  frontend/pages/profile/picture.tsx
  frontend/routes.js
  frontend/stores/modules/PostStore.ts
Labels: develop

#137 #136 이미지 업로드시 미리보기 컴포넌트가 나타나도록 처리
  frontend/components/Banner/Banner.tsx
  frontend/components/Editor/Editor.scss
  frontend/components/Editor/Editor.stories.tsx
  frontend/components/Editor/Editor.tsx
  frontend/components/Follow/Follow.tsx
  frontend/components/Friend/FriendItem.tsx
  frontend/components/Gallery/Gallery.scss
  frontend/components/Login/LoginFooter.tsx
  frontend/components/Login/LoginHeader.tsx
  frontend/components/Post/Post.scss
  frontend/components/Post/Post.tsx
  frontend/components/Post/PostCommentEditor.tsx
  frontend/components/Post/PostCommentItem.tsx
  frontend/components/Post/PostGallery.tsx
  frontend/components/common/Button/Button.tsx
  frontend/components/common/Header/Header.scss
  frontend/components/common/Header/Header.tsx
  frontend/components/common/Header/HeaderSearchBar.tsx
  frontend/containers/EditorContainer.tsx
  frontend/stores/modules/PostStore.ts
Labels: develop

#138 #135 댓글 기능 구현
  backend/src/models/Account.ts
  backend/src/models/Comment.ts
  backend/src/models/LikeComment.ts
  backend/src/models/LikePost.ts
  backend/src/models/LikeReplyComment.ts
  backend/src/models/Post.ts
  backend/src/models/ReplyComment.ts
  backend/src/routes/post/index.ts
  backend/src/routes/post/post.controller.ts
  backend/tslint.json
  frontend/api/post.ts
  frontend/components/Post/Post.tsx
  frontend/components/Post/PostCommentItem.tsx
  frontend/containers/PostContainer.tsx
  frontend/types/index.ts
Labels: develop

#141 #140 v1.1 버그 fix
  backend/src/routes/follow/follow.controller.ts
  backend/src/routes/follow/index.ts
  frontend/components/common/YoloHelmet/YoloHelmet.tsx
  frontend/components/common/YoloHelmet/index.ts
  frontend/containers/FriendContainer.tsx
  frontend/containers/PictureContainer.tsx
  frontend/package.json
  frontend/pages/_app.tsx
  frontend/static/images/favicon.ico
Labels: bug

#142 #139 버그 수정
  frontend/components/Post/Post.scss
  frontend/components/Post/Post.tsx
  frontend/components/Post/PostCommentItem.scss
  frontend/components/common/Header/Header.scss
Labels: bug

#143 #116 이미지 업로드시 사이즈 줄이기 적용
  backend/package.json
  backend/src/lib/multer.ts
  backend/src/lib/resizeImage.ts
  backend/src/lib/utils.ts
  backend/src/routes/follow/follow.controller.ts
  backend/src/routes/follow/index.ts
  backend/src/routes/post/post.controller.ts
  backend/src/routes/user/user.controller.ts
  frontend/components/Post/Post.scss
  frontend/components/Post/Post.tsx
  frontend/components/Post/PostCommentItem.scss
  frontend/components/common/Header/Header.scss
  frontend/components/common/YoloHelmet/YoloHelmet.tsx
  frontend/components/common/YoloHelmet/index.ts
  frontend/containers/FriendContainer.tsx
  frontend/containers/PictureContainer.tsx
  frontend/containers/ViewerContainer.tsx
  frontend/package.json
  frontend/pages/_app.tsx
  frontend/static/images/favicon.ico
  frontend/stores/modules/PostStore.ts
Labels: enhance
